controllers/HomeController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\ContactForm;

class HomeController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['admin'],
                'rules' => [
                    [
                        'actions' => ['admin'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            /*
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            */
        ];
    }

    public function actionIndex()
    {
        return $this->redirect(Yii::$app->user->getIsGuest() ? ['/image/index'] : ['/home/admin']);
    }

    public function actionAdmin()
    {
        return $this->render('admin');
    }

/*
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }
  */
}

controllers/UserController.php
<?php

namespace app\controllers;


use app\models\LoginForm;
use app\models\PasswordForm;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['password', 'logout'],
                'rules' => [
                    [
                        'actions' => ['password', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->getIsGuest()) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['/home/admin']);
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionPassword()
    {
        $model = new PasswordForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            /** @var User $user */
            $user = Yii::$app->user->identity;
            $user->setPassword($model->password);
            if ($user->save()) {
                return $this->redirect(['/home/admin']);
            }
        }
        return $this->render('password', [
            'model' => $model
        ]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\models\Article;
use app\models\Image;
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
$banner_article = null;
if ('image' == Yii::$app->controller->id) {
    $banners = 'edit' == Yii::$app->controller->action->id
        ? ['center' => [],'left' => [],'right' => []]
        : Image::getImages();
    if ('index' == Yii::$app->controller->action->id) {
        $banner_article = Yii::$app->view->render('@app/views/article/view', [
            'model' => Article::findOne('main')
        ]);
    }
}
else {
    $banners = Image::getImages(true);
}
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="generator" content="WordPress 3.6.1" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    $items = [
        ['label' => Yii::$app->user->getIsGuest() ? 'Главная' : 'Администрирования', 'url' => ['/home/index']]
    ];

    foreach (Article::getTitles('menu') as $id => $title) {
        $items[] = ['label' => $title, 'url' => ['/article/view', 'id' => $id]];
    }

    $items[] = Yii::$app->user->getIsGuest()
        ? ['label' => 'Вход', 'url' => ['/user/login']]
        : ['label' => 'Выход (' . Yii::$app->user->id . ')', 'url' => ['/user/logout']];

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => $items,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Alert::widget() ?>

        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>

        <?php
        if ($banner_article) {
            echo $banner_article;
        }
        ?>

        <div class="devil-center">
            <?= Yii::$app->view->render('@app/views/image/list', ['models' => $banners['center']]) ?>
        </div>

        <?= $content ?>
    </div>

    <div class="devil-left">
        <?= Yii::$app->view->render('@app/views/image/list', ['models' => $banners['left']]) ?>
    </div>

    <div class="devil-right">
        <?= Yii::$app->view->render('@app/views/image/list', ['models' => $banners['right']]) ?>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>