models/Image.php
<?php

namespace app\models;


use Yii;
use yii\db\ActiveRecord;

/**
 * @property string name
 * @property string url
 * @property string ext
 * @property string type
 * @property integer number
 */
class Image extends ActiveRecord
{
    public $file;
    public $image_url;

    public function rules()
    {
        return [
            [['number', 'banner'], 'required'],
            [['number', 'width', 'height'], 'integer'],
            ['banner', 'boolean'],
            [['html', 'image_url'], 'string'],
            ['name', 'string'],
//            ['ext', 'match', 'pattern' => '|^[a-z]$|'],
            [['url', 'ext'], 'string'],
            [['name', 'html', 'ext', 'url', 'width', 'height'], 'default', 'value' => null],
            ['number', 'default', 'value' => 0],
            ['banner', 'default', 'value' => false],
            ['type', 'in', 'range' => ['center', 'left', 'right']]
        ];
    }

    public function attributeLabels()
    {
        return [
            'name' => 'Название',
            'banner' => 'показывать всюда',
            'url' => 'Ссылка',
            'type' => 'Позиция',
            'number' => 'Номер',
            'html' => 'HTML',
            'width' => 'Ширина',
            'height' => 'Высота',
            'image_url' => 'Загрузить с сайта',
            'file' => 'Файл',
        ];
    }

    public function getPath($ext = null) {
        if (empty($ext)) {
            $ext = $this->ext;
        }
        return Yii::getAlias("@app/web/upload/$this->id.$ext");
    }

    public function getUrl($ext = null) {
        if (empty($ext)) {
            $ext = $this->ext;
        }
        return empty($ext) ? null : Yii::getAlias("@web/upload/$this->id.$ext");
    }

    public static function getImages($banner = false) {
        $query = static::find()->orderBy([
            'number' => SORT_ASC,
            'id' => SORT_ASC,
        ]);

        if ($banner) {
            $query->where('banner');
        }

        $images = [
            'center' => [],
            'left' => [],
            'right' => [],
        ];
        foreach($query->all() as $model) {
            /** @var Image $model */
            $images[$model->type][] = $model;
        }
        return $images;
    }
}

controllers/ImageController.php
<?php

namespace app\controllers;


use app\models\Image;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

class ImageController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['edit'],
                'rules' => [
                    [
                        'actions' => ['edit'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex() {
        return $this->render('index', Image::getImages());
    }

    public function actionEdit($id = null) {
        $model = $id ? $this->findModel($id) : new Image([
            'number' => 0,
            'banner' => false,
        ]);

        if ($model->load(Yii::$app->request->post())) {
            $transaction = Yii::$app->db->beginTransaction();
            if ($model->save()) {
                $file = UploadedFile::getInstance($model, 'file');
                if ($file || !empty($model->image_url)) {
                    if ($model->getOldAttribute('ext')) {
                        $path = $model->getPath($model->getOldAttribute('ext'));
                        if (file_exists($path)) {
                            unlink($path);
                        }
                    }
                    $file_loaded = false;
                    if ($model->image_url) {
                        $path = parse_url($model->image_url);
                        $extension = null;
                        if (preg_match('|\.(\w+)$|', $path['path'], $extension)) {
                            $model->ext = strtolower($extension[1]);
                            $content = file_get_contents($model->image_url);
                            if ($content) {
                                file_put_contents($model->getPath(), $content);
                                $file_loaded = true;
                            }
                        }
                    } else {
                        $model->ext = $file->getExtension();
                        $path = $model->getPath();
                        if (move_uploaded_file($file->tempName, $path)) {
                            $file_loaded = true;
                        }
                    }

                    if ($file_loaded) {
                        $model->save();
                        $transaction->commit();
                        return $this->redirect(['index']);
                    } else {
                        Yii::$app->session->addFlash('error', 'Невозможно сохранить файл');
                    }
                } elseif (!$model->isNewRecord) {
                    $model->save();
                    $transaction->commit();
                    return $this->redirect(['index']);
                } else {
                    Yii::$app->session->addFlash('error', 'Файл не загружен');
                }
            }
        }
        return $this->render('edit', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id) {
        $model = $this->findModel($id);
        if ($model->delete()) {
            if (file_exists($model->getPath())) {
                unlink($model->getPath());
            }
            Yii::$app->session->addFlash('success', 'Баннер удален');
        }
        else {
            Yii::$app->session->addFlash('error', 'Невозможно удалить баннер');
        }
        return $this->redirect(['index']);
    }

    /**
     * @param string $id
     * @return Image
     * @throws NotFoundHttpException
     */
    protected function findModel($id) {
        if (($model = Image::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Баннер не найден');
        }
    }
}

views/image/edit.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Баннер';

$types = [
    'center' => 'По центру',
    'left' => 'Слева',
    'right' => 'Справа',
];

$image_options = [
    'id' => 'preview',
    'class' => 'image'
];
if (empty($model->ext)) {
    $image_options['style'] = 'display: none';
}
?>
<div class="image-edit">
    <h1><?= $this->title ?></h1>

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

    <?= $form->field($model, 'name') ?>
    <?= $form->field($model, 'banner')->checkbox() ?>
    <?= $form->field($model, 'type')->dropDownList($types) ?>
    <?= $form->field($model, 'number') ?>
    <?= $form->field($model, 'html')->textarea() ?>
    <?php if (empty($model->html)): ?>
        <div id="simple-image-fields">
            <?= $form->field($model, 'url') ?>
            <?= $form->field($model, 'width') ?>
            <?= $form->field($model, 'height') ?>

            <?= $form->field($model, 'image_url') ?>
            или
            <?= $form->field($model, 'file')->fileInput([
                'accept' => 'image/*'
            ]) ?>
            <?= Html::img($model->getUrl(), $image_options) ?>
            <hr />
        </div>
    <?php endif ?>
    <?= Html::submitButton('Сохранить') ?>

    <?php ActiveForm::end() ?>
</div>

views/image/index.php
<?php
use app\models\Article;
use app\models\Image;
use app\widgets\ArticleView;
use yii\helpers\Html;

/** @var Image[] $center */
/** @var Image[] $left */
/** @var Image[] $right */

$this->title = 'Баннеры';
?>
<div class="image-index">
    <p>
        <?php
        if (!Yii::$app->user->getIsGuest()) {
            echo Html::a('Создать', ['edit'], ['class' => 'btn btn-primary']);
        }
        ?>
    </p>
</div>

views/image/list.php
<?php
use app\models\Image;
use yii\helpers\Html;

/** @var Image[] $models */
foreach($models as $model): ?>
    <div class="image">
        <?php
        $buttons = [];
        if ($model->name) {
            $buttons[] = Html::tag('span', $model->name);
        }
        if (!Yii::$app->user->getIsGuest()) {
            $buttons[] = Html::a('', ['/image/edit', 'id' => $model->id], ['class' => 'glyphicon glyphicon-edit']);
            $buttons[] = Html::a('', ['/image/delete', 'id' => $model->id], ['class' => 'glyphicon glyphicon-trash']);
        }
        if (count($buttons) > 0) {
            echo Html::tag('p', implode(' ', $buttons));
        }

        $image_options = [];
        foreach(['width', 'height'] as $name) {
            if (!empty($model->$name)) {
                $image_options[$name] = $model->$name;
            }
        }

        if (!empty($model->html)) {
            echo $model->html;
        }
        else {
            if ('swf' == $model->ext):
                ob_start();
                $image_options['type'] = 'application/x-shockwave-flash';
                $image_options['data'] = $model->getUrl();
                echo Html::beginTag('object', $image_options)
                ?>
                <param name="movie" value="<?= $model->getUrl() ?>"/>
                <param name="quality" value="high"/>
                <param name="scale" value="default"/>
                <?php
                echo Html::endTag('object');
                $img = ob_get_clean();
            else:
                $image_options['alt'] = $model->name;
                $img = Html::img($model->getUrl(), $image_options);
            endif;
            if ($model->url) {
                echo Html::a($img, $model->url, ['target' => '_blank']);
            } else {
                echo $img;
            }
        }
        ?>
    </div>
<?php endforeach ?>